### ISSUE TITLE
How to pre-fill a form for record update?

### ISSUE THREAD

**Issue by martinhbramwell** [wearebraid/vue-formulate-legacy#3]
The docs and demo need to show the steps to mutate the store so that the form is filled.

Is there a mutation for the entire form?  Must it be mutated one field at a time?

Where is the namespace used and how?

**Comment by justin-schroeder** [comment]
Yep, we need to add that to the docs too. Fields can be given an initial value with `:initial=“value”` and the entire form can be hydrated the same way `:initial=“{email: ‘justin@me.com’, name: ‘Justin’}”`.

**Comment by martinhbramwell** [comment]
... and namespace?  :-)

**Comment by justin-schroeder** [comment]
What about the namespace? Are you talking about module namespaces?

**Comment by martinhbramwell** [comment]
Yep.  The docs discuss namespaced modules, but if an external entity writes to the store what is the command?

Maybe your example could include a namespaced module, written to by the first one?

**Comment by martinhbramwell** [comment]
> Fields can be given an initial value with :initial=“value” and the entire form can be hydrated the same way :initial=“{email: ‘justin@me.com’, name: ‘Justin’}”.

I was unable to this, but I wonder how would I do it  an synchronous action sets the data in the Vuex state?  When I do this naively, the data appears but the validators do not know the data is there.  How can I tell the form that its fields have been filled?

**Comment by justin-schroeder** [comment]
Using direct mutations is not fully supported yet. Please see #6. Once support for that has been added we can update the docs to reflect it. However, the namespacing is just standard vuex namespacing. The current mutations are:

```
setFieldValue()
setFieldErrors()
setFieldValidationErrors()
setFieldMeta()
resetForm()
removeField()
```

To call them directly you just call `store.commit('setFieldValue', {form, field, value})`. To call them when using namespaces: `store.commit('namespace/setFieldValue', {form, field, value})` – but this is just standard vuex notation, not specific to `vue-formulate`.
