### ISSUE TITLE
How to use third-party tags?

### ISSUE THREAD

**Issue by martinhbramwell** [wearebraid/vue-formulate-legacy#4]
I was wanting to use [vue-cleave](https://www.npmjs.com/package/vue-cleave#examples).

How would I combine
 ```
<cleave placeholder="Enter your credit card number" :options="{ creditCard: true }"></cleave>
``` 
and
```
<formulate-element type="number" name="creditCard" label="Credit Card Number"/>
```
into a single input?

**Comment by justin-schroeder** [comment]
Custom inputs are supported. However, I'm not sure cleave will ever be a great match for pairing with `vue-formulate` as cleave tries to create a really similar api for creating forms as `vue-formulate`.

That said, feel free to use it and see what kind of millage you get. I've added an example of a custom input field to `0.7.3` and on [demo.vueformulate.com](https://demo.vueformulate.com). `vue-formulate` includes a handy dandy (yet undocumented) `mapModels()` which you can use really similarily to `mapState()` and `mapGetters()` provided by `vuex`. However I think this will suffer from the same bug as #6. To be addressed soon.

@martinhbramwell unfortunately you're experiencing the profound lack of documentation at the moment, but @wearebraid is currently working to get documentation pages and examples up in much more detail and legibility.

You're feedback is invaluable though at this early stage. Appreciate the patience.

**Comment by martinhbramwell** [comment]
I believe this tool kit will be a great time saver for what I have  to do, so I'm quite happy to be able to help out.
