### ISSUE TITLE
How to use 3rd party styling frameworks?

### ISSUE THREAD

**Issue by martinhbramwell** [wearebraid/vue-formulate-legacy#5]
I am  using Buefy & Bulma

To [style an element as a button](https://bulma.io/documentation/elements/button/#colors) with standardized colors, one can do:
```
<input class="button is-primary" type="submit" value="Submit input">
```
Unfortunately, if I try to do ...
```
<formulate-element class="button is-primary" type="submit" name="Save"/>
```
... I get an **unstyled** button sitting within a div styled with 'is-primary'.
```
<div class="button is-primary formulate-element formulate-element--type--submit">
    <div data-type="submit" data-classification="button" class="formulate-element-input-wrapper">
        <!---->
        <!---->
        <button type="submit">Save</button>
        <!---->
        <!---->
        <!---->
        <!---->
    </div>
    <!---->
</div>
```
Could you for example, provide `formulate-element` with an attribute, `inner-element-class`, whose value is added to the `class` attribute of `formulate-element`'s underlying button/input/select/etc ?

**Comment by martinhbramwell** [comment]
I fixed that specific issue, more or less, with :
```
div[class="formulate-element-input-wrapper"] button { 
    color: inherit;
    width: inherit;
      etc
      etc
      etc

 }
```
...but  I believe I'd need a long list of those :-(

**Comment by justin-schroeder** [comment]
I’ve debated adding some kind of support for inner classes or attributes. Might be worth doing. My main concern is people will use front end frameworks with lots of js layers that I don’t want to support. There is an undocumented way to use your own input elements. But perhaps adding classes wouldn’t be too bad.

**Comment by martinhbramwell** [comment]
The issue for me is that this upbeat remark in your docs...

> Absolutely zero styles are included so feel free to write your own!

...doesn't go on to say, "(except, the element you'll most want to style is inaccessible)"

:-)  See what I mean?

**Comment by justin-schroeder** [comment]
I do. Although like I said, this is largely intentional as they are easily styled by hand, just not by frameworks (which was kinda the point). Frameworks like bootstrap for example add lots of js and wrapper elements which `vue-formulate` will never support – so I suppose use at your own risk. If you do want to write your own styles the `.formulate-element-input-wrapper` always has a `data-classification` attribute which indicates the "type" of field, for example (scss):

```scss
[data-classification="text"] {
  input {
    // your custom textual input styles
  }
}

[data-classification="button"] {
  input, button {
    // your custom button styles
  }
}

[data-classification="select"] {
  select {
    // your custom select styles
  }
}
```

However, I also don't think its unreasonable to ask for class names on the actual input element. I'll add some kind of support for this.

**Comment by justin-schroeder** [comment]
@martinhbramwell `element-classes` attribute was added to `0.7.4`. Enjoy!
