### ISSUE TITLE
Missing required element in :initial values will lock up the browser

### ISSUE THREAD

**Issue by martinhbramwell** [wearebraid/vue-formulate-legacy#9]
Please refer to [the initialization of the example form in my Pull Request](https://github.com/wearebraid/vue-formulate/pull/8/commits/acc0e5e7a9e8cbb39fa37bc275de2d62a742c3ff#diff-583d740da0a74e8e6f1dea8b615daeb0R8) to understand the problem.

Removing any one of lines 9 -> 14 in the file [example/src/App.vue](https://github.com/warehouseman/vue-formulate/blob/acc0e5e7a9e8cbb39fa37bc275de2d62a742c3ff/example/src/App.vue) will cause some sort of deadlock that will consume all of available browser memory.

**Comment by justin-schroeder** [comment]
I can duplicate this bug – it seems to be caused by directly passing an object literal into `:initial`, if you make that object a `data()` property and pass that reference instead it should resolve this feature. However, obviously browser lockup isn't something that should occur so easily so I'll tag this for future.

**This breaks:**
```
<template>
<formulate
  name="myform""
  :initial="{surname: 'davis'}"
>
  <formulate-element
     name="firstname"
     type="text"
     validation="required"
  />
  <formulate-element
     name="surname"
     type="text"
     validation="required"
  />
</formulate-element>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>
```


**This works:**
```
<template>
<formulate
  name="myform""
  :initial="initialValues"
>
  <formulate-element
     name="firstname"
     type="text"
     validation="required"
  />
  <formulate-element
     name="surname"
     type="text"
     validation="required"
  />
</formulate-element>
</template>

<script>
export default {
  data () {
    return {
      initialValue: {surname: 'davis'}
    }
  }
}
</script>
```
